#!/usr/bin/env node
'use strict';

/**
 * Bundles client/ into public/app.js.
 *
 * Vendored rather than pulled from a CDN, deliberately. The submission stage is the
 * one place a player's plaintext number exists, so the code running there is part of
 * what has to be frozen. A <script src="https://some-cdn/…"> would leave the organiser
 * or the CDN able to serve different code to one player on the day — exactly the
 * manipulation the rest of the protocol rules out.
 *
 * The bundle's SHA-256 is written alongside so it can go into the freeze commit.
 *
 *   node tools/build-client.js                 build, write app.js + .sha256
 *   node tools/build-client.js --check         rebuild and diff against what is committed
 *   node tools/build-client.js --verify-hash   compare the committed bundle to its .sha256
 *   node tools/build-client.js --watch         rebuild on change (development)
 *
 * --check needs esbuild, so it belongs on a dev machine or in CI. --verify-hash needs
 * nothing at all, which is what the VPS runs: deployment installs with
 * `npm ci --omit=dev` and esbuild is a devDependency.
 *
 * Two things that will bite anyone regenerating this: tlock-js 0.9.0 is CommonJS, so
 * `export *` from it yields an empty module (esbuild cannot enumerate CJS names
 * statically) — re-export by name; and timelockEncrypt wants a Buffer, whose global
 * has to be installed from a module the entry point *imports*, not assigned in its
 * body, because module bodies run after all imports have been evaluated.
 */

const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const { render } = require('./md-to-page');

const ROOT = path.join(__dirname, '..');
const ENTRY = path.join(ROOT, 'client', 'index.jsx');
// docs/seating-design.md, rendered into the bundle so the app can explain itself
// without a network call and without a markdown library. See generateDesignDoc.
const GENERATED = path.join(ROOT, 'client', 'generated');
const DOCS = path.join(ROOT, 'docs');
const FIGURES_OUT = path.join(ROOT, 'public', 'figures');
const OUT = path.join(ROOT, 'public', 'app.js');
// esbuild emits the imported CSS as a sibling file rather than inlining it, so the
// freeze — and the hash that pins it — has to cover both artefacts.
const OUT_CSS = path.join(ROOT, 'public', 'app.css');
const SHIM = path.join(ROOT, 'client', 'buffer-shim.js');

const buildOptions = (outfile) => ({
  entryPoints: [ENTRY],
  outfile,
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2022'],
  jsx: 'automatic',
  minify: true,
  sourcemap: false,
  legalComments: 'none',
  inject: [SHIM],
  loader: { '.js': 'jsx', '.jsx': 'jsx' },
  define: { 'process.env.NODE_ENV': '"production"', global: 'globalThis' },
  logLevel: 'warning',
});

const sha = (buf) => crypto.createHash('sha256').update(buf).digest('hex');

/**
 * Render docs/seating-design.md (and its Chinese counterpart) into a module the client
 * imports, and copy the figures they reference into public/.
 *
 * The explanation page is generated rather than written twice, because it is the page
 * that tells a player why the draw cannot be steered: a copy that drifts from the
 * document under review is worse than no copy. It is regenerated on every build, so
 * editing the markdown is the only way to change it, and `--check` recomputes it from
 * the committed markdown before comparing hashes.
 *
 * The figures are static assets rather than inlined data: URIs. Two of them are 50 KiB
 * and 70 KiB of SVG, and putting 120 KiB of diagram into the bundle would make every
 * player download it in order to seal one number.
 */
function generateDesignDoc() {
  const docs = {
    en: render(fs.readFileSync(path.join(DOCS, 'seating-design.md'), 'utf8'), { imageBase: '/' }),
    zh: render(fs.readFileSync(path.join(DOCS, 'seating-design.zh.md'), 'utf8'), { imageBase: '/' }),
  };

  fs.mkdirSync(GENERATED, { recursive: true });
  const banner = '// GENERATED by tools/build-client.js from docs/seating-design{,.zh}.md — do not edit.';
  fs.writeFileSync(
    path.join(GENERATED, 'design-doc.js'),
    [banner, `export default ${JSON.stringify(docs, null, 2)};`, ''].join('\n')
  );

  fs.mkdirSync(FIGURES_OUT, { recursive: true });
  const figures = fs.readdirSync(path.join(DOCS, 'figures')).filter((f) => f.endsWith('.svg'));
  for (const f of figures) fs.copyFileSync(path.join(DOCS, 'figures', f), path.join(FIGURES_OUT, f));
  return { sections: docs.en.sections.length, figures: figures.length };
}

/** Digest of a js/css pair, in that order. Both ship to the player's browser. */
function digestOf(jsPath) {
  const cssPath = jsPath.replace(/\.js$/, '.css');
  return sha(Buffer.concat([
    fs.readFileSync(jsPath),
    fs.existsSync(cssPath) ? fs.readFileSync(cssPath) : Buffer.alloc(0),
  ]));
}

async function build(outfile) {
  const esbuild = require('esbuild'); // lazy: --verify-hash must work without devDeps
  generateDesignDoc();
  await esbuild.build(buildOptions(outfile));
  return { digest: digestOf(outfile), bytes: fs.statSync(outfile).size };
}

function verifyHash() {
  const shaFile = OUT + '.sha256';
  if (!fs.existsSync(OUT) || !fs.existsSync(shaFile)) {
    console.error('  FAIL  public/app.js or its .sha256 is missing from the checkout');
    return 1;
  }
  const expected = fs.readFileSync(shaFile, 'utf8').trim().split(/\s+/)[0];
  const actual = digestOf(OUT);
  if (expected !== actual) {
    console.error(`  FAIL  bundle does not match its committed hash\n        expected ${expected}\n        actual   ${actual}`);
    return 1;
  }
  console.log(`  OK    committed bundle matches its hash: ${actual}`);
  return 0;
}

async function watch() {
  const esbuild = require('esbuild');
  generateDesignDoc();
  const ctx = await esbuild.context({ ...buildOptions(OUT), minify: false });
  await ctx.watch();
  console.log('  watching client/ — rebuilding public/app.js on change (ctrl-c to stop)');
}

async function main() {
  if (process.argv.includes('--verify-hash')) return verifyHash();
  if (process.argv.includes('--watch')) { await watch(); return new Promise(() => {}); }

  const check = process.argv.includes('--check');
  // --check builds to a scratch name so a mismatching rebuild cannot overwrite the
  // committed artefacts it is meant to be comparing against.
  const target = check ? OUT.replace(/\.js$/, '.check.js') : OUT;
  const { digest, bytes } = await build(target);

  if (check) {
    fs.rmSync(target, { force: true });
    fs.rmSync(target.replace(/\.js$/, '.css'), { force: true });
    if (!fs.existsSync(OUT)) {
      console.error('  FAIL  public/app.js is missing — run: node tools/build-client.js');
      return 1;
    }
    const committed = digestOf(OUT);
    if (committed !== digest) {
      console.error(`  FAIL  committed bundle ${committed}\n        rebuild produces ${digest}`);
      return 1;
    }
    console.log(`  OK    bundle reproduces: sha256 ${digest}`);
    return 0;
  }

  fs.writeFileSync(OUT + '.sha256', `${digest}  public/app.js + public/app.css\n`);
  const v = (p) => require(path.join(ROOT, 'node_modules', p, 'package.json')).version;
  console.log(`  OK    public/app.js ${(bytes / 1024).toFixed(1)} KiB + public/app.css`);
  console.log('        docs/seating-design{,.zh}.md rendered into the bundle; figures copied to public/figures/');
  console.log(`        react ${v('react')}, tlock-js ${v('tlock-js')}, drand-client ${v('drand-client')}`);
  console.log(`        sha256 ${digest}`);
  console.log('        commit this file and its .sha256 as part of the freeze.');
  return 0;
}

main().then((code) => process.exit(code ?? 0)).catch((err) => {
  console.error(err);
  process.exit(1);
});
