#!/usr/bin/env node
'use strict';

/**
 * Bundles client/ into public/app.js.
 *
 * Vendored rather than pulled from a CDN, deliberately. The submission stage is the
 * one place a player's plaintext number exists, so the code running there is part of
 * what has to be frozen. A <script src="https://some-cdn/…"> would leave the organiser
 * or the CDN able to serve different code to one player on the day — exactly the
 * manipulation the rest of the protocol rules out.
 *
 * The bundle's SHA-256 is written alongside so it can go into the freeze commit.
 *
 *   node tools/build-client.js                 build, write app.js + .sha256
 *   node tools/build-client.js --check         rebuild and diff against what is committed
 *   node tools/build-client.js --verify-hash   compare the committed bundle to its .sha256
 *   node tools/build-client.js --watch         rebuild on change (development)
 *
 * --check needs esbuild, so it belongs on a dev machine or in CI. --verify-hash needs
 * nothing at all, which is what the VPS runs: deployment installs with
 * `npm ci --omit=dev` and esbuild is a devDependency.
 *
 * Two things that will bite anyone regenerating this: tlock-js 0.9.0 is CommonJS, so
 * `export *` from it yields an empty module (esbuild cannot enumerate CJS names
 * statically) — re-export by name; and timelockEncrypt wants a Buffer, whose global
 * has to be installed from a module the entry point *imports*, not assigned in its
 * body, because module bodies run after all imports have been evaluated.
 */

const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const { render } = require('./md-to-page');

const ROOT = path.join(__dirname, '..');
const ENTRY = path.join(ROOT, 'client', 'index.jsx');
// docs/seating-design.md, rendered into the bundle so the app can explain itself
// without a network call and without a markdown library. See generateDesignDoc.
const GENERATED = path.join(ROOT, 'client', 'generated');
const DOCS = path.join(ROOT, 'docs');
const FIGURES_OUT = path.join(ROOT, 'public', 'figures');
const OUT = path.join(ROOT, 'public', 'app.js');
// esbuild emits the imported CSS as a sibling file rather than inlining it, so the
// freeze — and the hash that pins it — has to cover both artefacts.
const OUT_CSS = path.join(ROOT, 'public', 'app.css');
const SHIM = path.join(ROOT, 'client', 'buffer-shim.js');
const NOTICES = path.join(ROOT, 'THIRD-PARTY-NOTICES.md');

const buildOptions = (outfile) => ({
  entryPoints: [ENTRY],
  outfile,
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2022'],
  jsx: 'automatic',
  minify: true,
  sourcemap: false,
  legalComments: 'none',
  inject: [SHIM],
  loader: { '.js': 'jsx', '.jsx': 'jsx' },
  define: { 'process.env.NODE_ENV': '"production"', global: 'globalThis' },
  // Which packages actually end up inside the bundle is a question with a precise
  // answer, and renderNotices below is the thing that needs it.
  metafile: true,
  logLevel: 'warning',
});

const sha = (buf) => crypto.createHash('sha256').update(buf).digest('hex');

/**
 * Render docs/seating-design.md (and its Chinese counterpart) into a module the client
 * imports, and copy the figures they reference into public/.
 *
 * The explanation page is generated rather than written twice, because it is the page
 * that tells a player why the draw cannot be steered: a copy that drifts from the
 * document under review is worse than no copy. It is regenerated on every build, so
 * editing the markdown is the only way to change it, and `--check` recomputes it from
 * the committed markdown before comparing hashes.
 *
 * The figures are static assets rather than inlined data: URIs. Two of them are 50 KiB
 * and 70 KiB of SVG, and putting 120 KiB of diagram into the bundle would make every
 * player download it in order to seal one number.
 */
function generateDesignDoc() {
  const docs = {
    en: render(fs.readFileSync(path.join(DOCS, 'seating-design.md'), 'utf8'), { imageBase: '/' }),
    zh: render(fs.readFileSync(path.join(DOCS, 'seating-design.zh.md'), 'utf8'), { imageBase: '/' }),
  };

  fs.mkdirSync(GENERATED, { recursive: true });
  const banner = '// GENERATED by tools/build-client.js from docs/seating-design{,.zh}.md — do not edit.';
  fs.writeFileSync(
    path.join(GENERATED, 'design-doc.js'),
    [banner, `export default ${JSON.stringify(docs, null, 2)};`, ''].join('\n')
  );

  fs.mkdirSync(FIGURES_OUT, { recursive: true });
  const figures = fs.readdirSync(path.join(DOCS, 'figures')).filter((f) => f.endsWith('.svg'));
  for (const f of figures) fs.copyFileSync(path.join(DOCS, 'figures', f), path.join(FIGURES_OUT, f));
  return { sections: docs.en.sections.length, figures: figures.length };
}

/**
 * Build the text of THIRD-PARTY-NOTICES.md from what is actually in the bundle.
 *
 * `public/app.js` is committed — the submission page is where a player's plaintext
 * number exists, so the code running there is part of what the freeze commits to. That
 * makes this repository a *binary distribution* of every library compiled into it, and
 * their licences have things to say about that: MIT asks that its notice travel with
 * any substantial portion, and `ieee754` is BSD-3-Clause, whose second condition names
 * binary redistribution explicitly. `legalComments: 'none'` keeps those notices out of
 * the bundle, so they have to live somewhere; this is where. The caller writes it,
 * or compares it under --check.
 *
 * Generated from esbuild's metafile rather than from a list somebody maintains. A
 * hand-written list is correct on the day it is written: the bundle carries seventeen
 * packages, of which four were obvious and thirteen arrived as transitive dependencies
 * of tlock-js. The next one to arrive would not announce itself either.
 */
function renderNotices(metafile) {
  const bytes = new Map();
  for (const [file, info] of Object.entries(metafile.inputs)) {
    const m = /node_modules\/((?:@[^/]+\/)?[^/]+)\//.exec(file.replace(/\\/g, '/'));
    if (m) bytes.set(m[1], (bytes.get(m[1]) || 0) + info.bytes);
  }

  // Where a package is dual-licensed, take MIT: it is this project's own licence, and
  // saying which half of an "Apache-2.0 OR MIT" was taken is part of taking it.
  const licenceFile = (dir) => {
    for (const name of ['LICENSE-MIT', 'LICENSE', 'LICENCE', 'LICENSE.md', 'license']) {
      const f = path.join(dir, name);
      if (fs.existsSync(f)) return { file: name, text: fs.readFileSync(f, 'utf8').trim() };
    }
    return null;
  };

  const packages = [...bytes.keys()].sort().map((name) => {
    const dir = path.join(ROOT, 'node_modules', name);
    const pkg = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
    const declared = typeof pkg.license === 'string' ? pkg.license : pkg.license?.type;
    const lic = licenceFile(dir);
    // Not a warning. A package whose terms we cannot reproduce is one we cannot
    // redistribute, and the bundle is redistribution.
    if (!lic) throw new Error(`build-client: ${name} ships no licence file; add its terms by hand`);
    return { name, version: pkg.version, declared: declared || '(not declared)', ...lic };
  });

  const FENCE = '```';
  const out = [
    '# Third-party notices',
    '',
    '> **Generated by `tools/build-client.js` from the bundle itself — do not edit.**',
    '',
    "This project is MIT licensed; see [`LICENSE`](LICENSE). What follows covers the",
    'libraries compiled into `public/app.js`, which is committed here because the page',
    "that seals a player's number is part of what the freeze commits to",
    '(`docs/PROTOCOL.md` §4.1). The bundle is therefore a binary distribution of each of',
    'them, and since it is built with `legalComments: \'none\'` their notices are',
    'reproduced below rather than inside it.',
    '',
    'Where a package offers "Apache-2.0 OR MIT", the MIT terms are the ones taken.',
    '',
    '| Package | Version | Licence |',
    '|---|---|---|',
    ...packages.map((x) => `| \`${x.name}\` | ${x.version} | ${x.declared} |`),
    '',
  ];

  for (const x of packages) {
    out.push(
      `## ${x.name} ${x.version}`,
      '',
      `Declared \`${x.declared}\`; text below from \`node_modules/${x.name}/${x.file}\`.`,
      '',
      FENCE,
      x.text,
      FENCE,
      ''
    );
  }

  return { text: out.join('\n'), count: packages.length };
}

/** Digest of a js/css pair, in that order. Both ship to the player's browser. */
function digestOf(jsPath) {
  const cssPath = jsPath.replace(/\.js$/, '.css');
  return sha(Buffer.concat([
    fs.readFileSync(jsPath),
    fs.existsSync(cssPath) ? fs.readFileSync(cssPath) : Buffer.alloc(0),
  ]));
}

async function build(outfile, { check = false } = {}) {
  const esbuild = require('esbuild'); // lazy: --verify-hash must work without devDeps
  generateDesignDoc();
  const result = await esbuild.build(buildOptions(outfile));

  // --check must leave the tree exactly as it found it; that is why it builds to a
  // scratch name at all. So under --check the notices are compared rather than written,
  // which is the stronger check anyway: a dependency added without a rebuild leaves a
  // committed notices file that no longer covers the committed bundle, and CI runs this
  // on a clone nobody has touched.
  const notices = renderNotices(result.metafile);
  if (check) {
    // Compared with line endings normalised. This file is not byte-pinned — nothing
    // hashes it — so a CR here means a checkout setting, and reporting that as "the
    // notices no longer cover the bundle" would send the reader somewhere useless.
    // test/checkout.test.js is where line endings are actually policed.
    const lf = (s) => s.replace(/\r\n/g, '\n');
    notices.stale = !fs.existsSync(NOTICES) || lf(fs.readFileSync(NOTICES, 'utf8')) !== lf(notices.text);
  } else {
    fs.writeFileSync(NOTICES, notices.text);
  }
  return { digest: digestOf(outfile), bytes: fs.statSync(outfile).size, notices };
}

function verifyHash() {
  const shaFile = OUT + '.sha256';
  if (!fs.existsSync(OUT) || !fs.existsSync(shaFile)) {
    console.error('  FAIL  public/app.js or its .sha256 is missing from the checkout');
    return 1;
  }
  const expected = fs.readFileSync(shaFile, 'utf8').trim().split(/\s+/)[0];
  const actual = digestOf(OUT);
  if (expected !== actual) {
    console.error(`  FAIL  bundle does not match its committed hash\n        expected ${expected}\n        actual   ${actual}`);
    return 1;
  }
  console.log(`  OK    committed bundle matches its hash: ${actual}`);
  return 0;
}

async function watch() {
  const esbuild = require('esbuild');
  generateDesignDoc();
  const ctx = await esbuild.context({ ...buildOptions(OUT), minify: false });
  await ctx.watch();
  console.log('  watching client/ — rebuilding public/app.js on change (ctrl-c to stop)');
}

async function main() {
  if (process.argv.includes('--verify-hash')) return verifyHash();
  if (process.argv.includes('--watch')) { await watch(); return new Promise(() => {}); }

  const check = process.argv.includes('--check');
  // --check builds to a scratch name so a mismatching rebuild cannot overwrite the
  // committed artefacts it is meant to be comparing against.
  const target = check ? OUT.replace(/\.js$/, '.check.js') : OUT;
  const { digest, bytes, notices } = await build(target, { check });

  if (check) {
    fs.rmSync(target, { force: true });
    fs.rmSync(target.replace(/\.js$/, '.css'), { force: true });
    if (!fs.existsSync(OUT)) {
      console.error('  FAIL  public/app.js is missing — run: node tools/build-client.js');
      return 1;
    }
    const committed = digestOf(OUT);
    if (committed !== digest) {
      console.error(`  FAIL  committed bundle ${committed}\n        rebuild produces ${digest}`);
      return 1;
    }
    if (notices.stale) {
      console.error('  FAIL  THIRD-PARTY-NOTICES.md does not match the bundle');
      console.error('        run: node tools/build-client.js');
      return 1;
    }
    console.log(`  OK    bundle reproduces: sha256 ${digest}`);
    console.log(`  OK    THIRD-PARTY-NOTICES.md covers its ${notices.count} packages`);
    return 0;
  }

  fs.writeFileSync(OUT + '.sha256', `${digest}  public/app.js + public/app.css\n`);
  const v = (p) => require(path.join(ROOT, 'node_modules', p, 'package.json')).version;
  console.log(`  OK    public/app.js ${(bytes / 1024).toFixed(1)} KiB + public/app.css`);
  console.log('        docs/seating-design{,.zh}.md rendered into the bundle; figures copied to public/figures/');
  console.log(`        THIRD-PARTY-NOTICES.md covers the ${notices.count} packages compiled into it`);
  console.log(`        react ${v('react')}, tlock-js ${v('tlock-js')}, drand-client ${v('drand-client')}`);
  console.log(`        sha256 ${digest}`);
  console.log('        commit this file and its .sha256 as part of the freeze.');
  return 0;
}

main().then((code) => process.exit(code ?? 0)).catch((err) => {
  console.error(err);
  process.exit(1);
});
